# Basic Python

## 1. Split this string

In [1]:
s = "Hi there Sam!"

In [2]:
format(s)

'Hi there Sam!'

*`italicized text`*## 2. Use .format() to print the following string. 

### Output should be: The diameter of Earth is 12742 kilometers.

In [3]:
planet = "Earth"
diameter = 12742

In [4]:
format(planet)

'Earth'

In [5]:
format(diameter)

'12742'

## 3. In this nest dictionary grab the word "hello"

In [ ]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

In [6]:
format(s)

'Hi there Sam!'

# Numpy

In [ ]:
import numpy as np

## 4.1 Create an array of 10 zeros? 
## 4.2 Create an array of 10 fives?

In [7]:
import numpy as np
arr=np.array([0,0,0,0,0,0,0,0,0])
print("***Numpy array items***")
print(arr)

***Numpy array items***
[0 0 0 0 0 0 0 0 0]


In [8]:
import numpy as np
arr=np.array([5,5,5,5,5,5,5,5,5])
print("***Numpy array items***")
print(arr)

***Numpy array items***
[5 5 5 5 5 5 5 5 5]


## 5. Create an array of all the even integers from 20 to 35

In [9]:
import numpy as np
arr=np.array([22,24,26,28,30,32,34])
print("numpy array items")
print(arr)

numpy array items
[22 24 26 28 30 32 34]


## 6. Create a 3x3 matrix with values ranging from 0 to 8

In [10]:
import numpy as np 
x=np.arange(0,9).reshape (3,3)
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


## 7. Concatinate a and b 
## a = np.array([1, 2, 3]), b = np.array([4, 5, 6])

In [11]:
import numpy as np 
a=np.array ([1,2,3])
b=np.array ([4,5,6])
c=np.concatenate((a,b),axis=0)
print(c)

[1 2 3 4 5 6]


# Pandas

## 8. Create a dataframe with 3 rows and 2 columns

In [ ]:
import pandas as pd


In [12]:
import pandas as pd
data=[{'a':1,'b':2,'c':3},{'a':10,'b':20,'c':30}]
df=pd.DataFrame(data)
df

a   b   c
0   1   2   3
1  10  20  30

## 9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023

In [13]:
import pandas as pd
df=pd.date_range(start='1-1-2023',end='2-1-2023',freq='5H')
df

DatetimeIndex(['2023-01-01 00:00:00', '2023-01-01 05:00:00',
               '2023-01-01 10:00:00', '2023-01-01 15:00:00',
               '2023-01-01 20:00:00', '2023-01-02 01:00:00',
               '2023-01-02 06:00:00', '2023-01-02 11:00:00',
               '2023-01-02 16:00:00', '2023-01-02 21:00:00',
               ...
               '2023-01-29 23:00:00', '2023-01-30 04:00:00',
               '2023-01-30 09:00:00', '2023-01-30 14:00:00',
               '2023-01-30 19:00:00', '2023-01-31 00:00:00',
               '2023-01-31 05:00:00', '2023-01-31 10:00:00',
               '2023-01-31 15:00:00', '2023-01-31 20:00:00'],
              dtype='datetime64[ns]', length=149, freq='5H')

## 10. Create 2D list to DataFrame

lists = [[1, 'aaa', 22],
         [2, 'bbb', 25],
         [3, 'ccc', 24]]

In [ ]:
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]

In [14]:
import pandas as pd
lists= [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]
df=pd.DataFrame(lists,columns=['no','name','age'],dtype=float)
df

/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py:3326: FutureWarning: Could not cast to float64, falling back to object. This behavior is deprecated. In a future version, when a dtype is passed to 'DataFrame', either all columns will be cast to that dtype, or a TypeError will be raised
  exec(code_obj, self.user_global_ns, self.user_ns)


no name   age
0  1.0  aaa  22.0
1  2.0  bbb  25.0
2  3.0  ccc  24.0